# Generated by Django 5.2.7 on 2025-10-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_alter_blogpost_content_alter_compound_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_plan_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='map_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
