# Generated by Django 5.2.7 on 2025-10-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_developer_logo_alter_property_floor_plan_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
