# Generated by Django 5.2.7 on 2025-10-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_alter_blogpost_image_alter_compound_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='compounds/main_images/'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='developers/logos/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/floor_plans/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/main_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/map_images/'),
        ),
    ]
